server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3307/foodapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: food
    password: food
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    issuer: "foodapp-auth"
    expires-min: 15
    # HS256 secret for now (32+ chars). Later we’ll switch to RSA keys + JWKS.
    secret: "this-is-a-dev-only-secret-change-in-prod-1234567890"
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChYq6UAyUk+GgqYM5X1OP6DC1LUyoufe3BVf63ZNINxpW5RrOIdgNGdD1ExIxLOOh6GX69fhQ94dQxjxEzSIzYMrntWCjYY4zh8g5gSKUSA3HsT05YkI12x2/Tmunnp4jeK4ihd1uRquP1AXh8DGmcuNYS6gaLtV9UEEiR7NTGMN4xWRTqrYafQMT4QQoW8m2eCvjM13VPl3L6r/WGSXhVLdwTWjvY3mFhbALtSBBm1F0aLMD5y+IQaq+vmRXjMsqHT+/X84QTEyozJbTnnw851SYL0ZYhf9+8VYugQjCk/8WCEAwDlLi4BM/v4KolMWDB/uGPqf7yxJC0EupLbUIpAgMBAAECggEAM+M1fBMyyxsu6okrbqPdFJT7rx8zDbWhTqrmdXJt8s3pb6Nir7o5vVo8JLMI5FqMrE0sKaKywV6tSa3U+ucVmaFdlAjnQQNo1XBs3NoecJc49qBc8S6wvQLMWn2RPNDpuXzHthpZD5GhLzHk2gVno2LuOTCTIDIVT0LZAknh80JZqIqfFiyXBgXRSTHy039XxMjWzZEimPD9zu0YFMUyKsM/b0ulo03Fl0LJQRaSvRl+mxFEw5n4p2ccdqtwuurF38ro2EM88P5QEsilv6faB+aw5Ra5EeE7b49xD4paFArK85RLJkO+zBYMS2d1mpsvqZw/I5gv0cwCYh/U7eXqbQKBgQDgOh3HgxPb+Z2qTmJFfj85hea68WcZwFbmziDeaCulNVP/GO98SedB5Py82dCQ46kDLKHtqOZGsrydHPfrsWBish8F4qVM2t34NkCZSwf6nKsvU0q7/EP6VxKKao7GHqB5mD3isf8zmkTlchRLXBm9/xNpebFRB1+lRR8E0oeiDwKBgQC4QPmgkd84MTYbrxdx1FCoDwvjGKLcV6ACKGrMyg0rK+9Enj0OIRTH7MmotNZThfwz+n69JRn99CpQXgYY4Jv0W6autBlEIa4CEch9U1vCQZKukXV9HDQLMeIngUDBNMEQFc+Z5oAi4+68MlqBiDFaUSdntdqB4+mKUlaY8kuwRwKBgEc2berFWHNOjaJfDprfg5jzS9onfQUSrwbShGHeV646h5jHBJhGqGmnHhWkX7cEdtMJQ8xFDg16CqkjYCG8zc3KoEuwNat4/3IrWMzWpYwUYdG/9EZL0hMZwEuxl/KYG4NCtLTgrxpmbmcomgVtFMfg0Pt4qLYBT4EfuMBBVM5FAoGBAIeNzdjy2I1Hry4Iz6+/6qLphu5JVq/Si3Zq87+8OpnzVbFe1T5K2jYHn4jNmgySuywmcw2GeSvbcTH1Knks7a+FqghHmXsFaDY/jQeexxgQE/D4NL6ZfDRsO5yiu9gojozd7wCjksuYcy/jv7AiWWS/5cSoBpye51cLIoidYU/LAoGAZ9XLaUAsQr5ICIlWtLzhq+/jHRbaghZ5FiaeREJZJrUap14bsi0CIDP1k7EsWhOCVjnQJTH2Fb/7KKEH2bIAMMCdG10Q6tqGZ+/ikNDsOrFZJX7Gff8qnCNFnXtgp9XTwAJiTenDQFaxot5CdXIOt6S5jyhB7DUs09/Yl+G1kzs=
      -----END PRIVATE KEY-----
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoWKulAMlJPhoKmDOV9Tj+gwtS1MqLn3twVX+t2TSDcaVuUaziHYDRnQ9RMSMSzjoehl+vX4UPeHUMY8RM0iM2DK57Vgo2GOM4fIOYEilEgNx7E9OWJCNdsdv05rp56eI3iuIoXdbkarj9QF4fAxpnLjWEuoGi7VfVBBIkezUxjDeMVkU6q2Gn0DE+EEKFvJtngr4zNd1T5dy+q/1hkl4VS3cE1o72N5hYWwC7UgQZtRdGizA+cviEGqvr5kV4zLKh0/v1/OEExMqMyW0558POdUmC9GWIX/fvFWLoEIwpP/FghAMA5S4uATP7+CqJTFgwf7hj6n+8sSQtBLqS21CKQIDAQAB
      -----END PUBLIC KEY-----
