services:
  mysql:
    image: mysql:8.0
    container_name: fd_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foodapp
      - MYSQL_USER=food
      - MYSQL_PASSWORD=food
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password","--lower_case_table_names=1"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot | grep 'mysqld is alive' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: fd_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.6.1
#    container_name: fd_zookeeper
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#      - ZOO_ENABLE_AUTH=no
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    ports:
#      - "2181:2181"
#    healthcheck:
#      test: ["CMD-SHELL", "echo ruok | nc -w 2 127.0.0.1 2181 | grep imok || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 10

#  kafka:
#    image: confluentinc/cp-kafka:7.6.1
#    container_name: fd_kafka
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    environment:
#      - KAFKA_ENABLE_KRAFT=no
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_BROKER_ID=1
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    ports:
#      - "9092:9092"   # internal (containers)
#      - "9094:9094"   # external (your laptop)
#    healthcheck:
#      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
#      interval: 15s
#      timeout: 10s
#      retries: 15

volumes:
  mysql_data:
